

[window]
opacity = 1

  [window.padding]
  x = 10
  y = 10

[font]
size = 11

[colors.primary]
background = "#1c1c1c"
foreground = "#E9E9E9"

[colors.cursor]
text = "#161616"
cursor = "#f2f4f8"

[colors.normal]
black   = "#2f383e"     # darker base for contrast
red     = "#F85552"     # your chosen red
green   = "#8DA101"     # your chosen green
yellow  = "#DFA000"     # your chosen yellow
blue    = "#3A94C5"     # your chosen blue
magenta = "#c678dd"     # gentle magenta, slightly modernized
cyan    = "#5FB3B3"     # calm cyan, still visible
white   = "#D5C9AB"     # softened warm white

[colors.bright]
black   = "#475258"     # Everforest’s deep gray
red     = "#F97B72"     # bright version of your red
green   = "#A7C080"     # bright Everforest green
yellow  = "#E6C384"     # brighter, softer yellow
blue    = "#6CB6EB"     # bright version of your blue
magenta = "#D699B6"     # keep for consistency
cyan    = "#83C092"     # slight bright bump
white   = "#FDF6E3"     # warm, readable light

