window:
  opacity: 0.95
  padding:
    x: 5
    y: 5

colors:
  primary:
    background: '#ea1717'
    foreground: '#173bea'

cursor:
  style: Beam
  blink: On

selection:
  save_to_clipboard: true

live_config_reload: true
